In [1]:
import numpy as np
import pandas as pd

# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Sim

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [2]:
genes = ["TP53", "TNF", "IL6", "IGF2", "BRCA1"]

lista1 = [len(genes[0]), genes[0][:2], genes[0].lower().count('a'), 'hu' in genes[0].lower()]
lista2 = [len(genes[1]), genes[1][:2], genes[1].lower().count('a'), 'hu' in genes[1].lower()]
lista3 = [len(genes[2]), genes[2][:2], genes[2].lower().count('a'), 'hu' in genes[2].lower()]
lista4 = [len(genes[3]), genes[3][:2], genes[3].lower().count('a'), 'hu' in genes[3].lower()]
lista5 = [len(genes[4]), genes[4][:2], genes[4].lower().count('a'), 'hu' in genes[4].lower()]

obj_comp_multidim = [lista1, lista2, lista3, lista4, lista5]

print (obj_comp_multidim)

[[4, 'TP', 0, False], [3, 'TN', 0, False], [3, 'IL', 0, False], [4, 'IG', 0, False], [5, 'BR', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [3]:
obj_comp_multidim = [lista1, lista2, lista3, lista4, lista5]

array1 = np.array(obj_comp_multidim)

print(array1)

[['4' 'TP' '0' 'False']
 ['3' 'TN' '0' 'False']
 ['3' 'IL' '0' 'False']
 ['4' 'IG' '0' 'False']
 ['5' 'BR' '1' 'False']]

## 4 – Recupere todos os itens do terceiro gene.

In [4]:
array1[2,:]
print(array1[2,:])

['3' 'IL' '0' 'False']

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [8]:
array1[:, -1]

array(['False', 'False', 'False', 'False', 'False'], dtype='<U21')

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [10]:
array1[[1, 3], 1:3]

array([['TN', '0'],
       ['IG', '0']], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [23]:
dicionario_lista_genes = {
    genes[0]: lista1,
    genes[1]: lista2,
    genes[2]: lista3,
    genes[3]: lista4,
    genes[4]: lista5
}

df = pd.DataFrame(dicionario_lista_genes)
df

    TP53    TNF    IL6   IGF2  BRCA1
0      4      3      3      4      5
1     TP     TN     IL     IG     BR
2      0      0      0      0      1
3  False  False  False  False  False

In [41]:
df = df.transpose()

df.rename(columns={
    0: 'letras',
    1: 'primeiras',
    2: 'a',
    3: 'hu'
    }, inplace=True)

df

      letras primeiras  a     hu
TP53       4        TP  0  False
TNF        3        TN  0  False
IL6        3        IL  0  False
IGF2       4        IG  0  False
BRCA1      5        BR  1  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [ ]:
df = pd.DataFrame(dicionario_lista_genes)


num_caracteres = df.iloc[0]
quantidade_a = df.iloc[2]

print(num_caracteres)
print(quantidade_a)

TP53     4
TNF      3
IL6      3
IGF2     4
BRCA1    5
Name: 0, dtype: object
TP53     0
TNF      0
IL6      0
IGF2     0
BRCA1    1
Name: 2, dtype: object

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [ ]:
df = pd.DataFrame(dicionario_lista_genes)

df.iloc[3, [0, 3]]

TP53    False
IGF2    False
Name: 3, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [ ]:
df_csv = pd.read_csv("data.csv")


num_entradas = len(df_csv)
classes_colunas = list(df_csv.dtypes)
contagem_classes = df_csv.dtypes.value_counts().tolist()
colunas = [df_csv.iloc[:,0], df_csv.iloc[:,3], df_csv.iloc[:,8]]
medias = [col.mean() for col in colunas]
desvios = [col.std() for col in colunas]
terceiro_quartil = [col.quantile(0.75) for col in colunas]

dicio_df_csv = {
    "num_entradas": num_entradas,
    "classes_colunas": classes_colunas,
    "contagem_classes": contagem_classes,
    "medias": medias,
    "desvios_padrao": desvios,
    "terceiro_quartil": terceiro_quartil
}

print(dicio_df_csv)

{'num_entradas': 36634, 'classes_colunas': [dtype('int64'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('int64')], 'contagem_classes': [11, 4, 3], 'medias': [np.float64(548661.9371894961), np.float64(731478.0068460993), np.float64(2571004.0973420865)], 'desvios_padrao': [np.float64(259912.9264939009), np.float64(17523003.588415086), np.float64(20367766.569178067)], 'terceiro_quartil': [np.float64(774252.0), np.float64(0.0), np.float64(1128871.1824999999)]}