# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [20]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

p and q and r and s and t

False

In [21]:
not (p and q and r and s and t)

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [22]:
#substitui o simbolo do meio por or
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

p or q or r or s or t or u

True

In [23]:
not (p or q or r or s or t or u)

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [24]:
#segunda = terceira or terceira = quarta
#df.iloc[1,:] == df.iloc[2,:] or df.iloc[2,:] == df.iloc[3,:]

df_importada = pd.read_csv('df_mil_arrays.csv', index_col='Unnamed: 0')
df_importada = df_importada.round(3)

comparacao = (df_importada.iloc[1].equals(df_importada.iloc[2])) or (df_importada.iloc[2].equals(df_importada.iloc[3]))

comparacao

False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [25]:
linha1 = df_importada.iloc[0]

resultado = (linha1 >= 10).all()

resultado

np.False_

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [26]:
C = df_importada.iloc[:, 2]

resultado = ((C >= 0) & (C <= 40)).all()

resultado

np.True_

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [27]:
ultima_linha = df_importada.iloc[-1]

resultado = (ultima_linha > 10).any()

resultado

np.False_

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [28]:
df_filtrado = df_importada[(df_importada > 5) & (df_importada < 7)]

df_filtrado

                  A   B      C   D  medias_linha
linha1          NaN NaN  5.893 NaN           NaN
linha2          NaN NaN    NaN NaN           NaN
linha3          NaN NaN    NaN NaN           NaN
linha4        5.893 NaN    NaN NaN           NaN
linha5          NaN NaN    NaN NaN           NaN
media_coluna    NaN NaN    NaN NaN         5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [29]:
df_filtrado = df_importada[(df_importada <= 5) | (df_importada > 7)]

df_filtrado

                  A       B      C       D  medias_linha
linha1        1.612   1.673    NaN   0.263         2.360
linha2        0.372   2.600  2.800  34.729        10.125
linha3        0.069   0.139  1.612   1.673         0.873
linha4          NaN   0.263  0.372   2.600         2.282
linha5        2.800  34.729  0.069   0.139         9.434
media_coluna  2.149   7.881  2.149   7.881           NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [30]:
arrays = df_importada.iloc[:, -2:].to_numpy()

array1 = arrays[:, 0]
array2 = arrays[:, 1]

resultado = np.any((array1 >= 2) & (array1 <= 5))

resultado

np.True_

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [31]:
resultado = np.all((arrays > -1) & (arrays < 12))

resultado

np.False_

In [32]:
import numpy as np
import pandas as pd